repos:
  - repo: https://github.com/pycqa/isort
    rev: 7.0.0
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black"]
  #- repo: https://github.com/psf/black
  #  rev: 25.9.0
  #  hooks:
  #    - id: black
  #      language_version: python3.13
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.14.1
    hooks:
      # Run the linter.
      - id: ruff-check
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.9.5
    hooks:
      - id: uv-export
        args: ["--no-emit-project", "--frozen", "--output-file=requirements.txt", "--quiet"]
  - repo: https://gitlab.com/saferatday0/badgie
    rev: "0.14.2"
    hooks:
      - id: badgie